load 'plugins.rake'

plugin 'vim-fugitive', 'git://github.com/tpope/vim-fugitive.git'
plugin 'ctrlp.vim', 'git://github.com/kien/ctrlp.vim.git'
plugin 'vim-ruby', 'git://github.com/vim-ruby/vim-ruby'
plugin 'vim-rails', 'git://github.com/tpope/vim-rails.git'
plugin 'supertab', 'git://github.com/ervandew/supertab.git'
plugin 'tagbar', 'git://github.com/majutsushi/tagbar.git'
plugin 'vim-colors-solarized', 'git://github.com/altercation/vim-colors-solarized.git'
plugin 'vim-coffee-script', 'git://github.com/kchmck/vim-coffee-script.git'
plugin 'vim-indent-object', 'git://github.com/michaeljsmith/vim-indent-object.git'
plugin 'vim-haml', 'git://github.com/tpope/vim-haml.git'
plugin 'vim-unimpaired', 'git://github.com/tpope/vim-unimpaired.git'
plugin 'vim-surround', 'git://github.com/tpope/vim-surround.git'
plugin 'vim-endwise', 'git://github.com/tpope/vim-endwise.git'
plugin 'vim-cucumber', 'git://github.com/tpope/vim-cucumber.git'
plugin 'vim-sensible', 'git://github.com/tpope/vim-sensible.git'
plugin 'syntastic', 'git://github.com/scrooloose/syntastic.git'
plugin 'gundo.vim', 'git://github.com/sjl/gundo.vim.git'
plugin 'vim-commentary', 'git://github.com/tpope/vim-commentary.git'
plugin 'tabular', 'git://github.com/godlygeek/tabular.git'
plugin 'bufexplorer', 'git://github.com/jlanzarotta/bufexplorer.git'
plugin 'vim-easymotion', 'git://github.com/Lokaltog/vim-easymotion.git'
plugin 'YankRing.vim', 'git://github.com/vim-scripts/YankRing.vim.git'
plugin 'powerline', 'git://github.com/Lokaltog/powerline.git'
plugin 'vim-conque', 'git://github.com/basepi/vim-conque.git'
plugin 'vim-indent-guides', 'git://github.com/nathanaelkane/vim-indent-guides.git'
plugin 'vim-matchit', 'git://github.com/edsono/vim-matchit.git'
plugin 'rainbow_parentheses', 'git://github.com/kien/rainbow_parentheses.vim.git'
plugin 'vim-emblem', 'https://github.com/heartsentwined/vim-emblem.git'
plugin 'gist-vim', 'git://github.com/mattn/gist-vim.git'
plugin 'webapi-vim', 'git://github.com/mattn/webapi-vim.git'
plugin 'nerdtree', 'git://github.com/scrooloose/nerdtree.git'
plugin 'emmet-vim', 'git://github.com/mattn/emmet-vim.git'

plugin 'AutoTag', 'git@github.com:vim-scripts/AutoTag.git'
# plugin 'vim-textobj-rubyblock', 'git@github.com:nelstrom/vim-textobj-rubyblock.git'
